services:
  postgres:
    image: postgres:13
    container_name: fma_postgres_db
    environment:
      POSTGRES_USER: common-user-aph # Change this
      POSTGRES_PASSWORD: aph1234 # Change this
      POSTGRES_DB: fma_db # The database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: